In [1]:

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Requirement already satisfied: xlrd in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [3]:
import pandas as pd
import numpy as np

In [4]:
ratings = pd.read_csv(
    "/content/drive/MyDrive/HYBRID RECOMMENDER SYSTEM/ratings.dat",
    sep="::",
    engine="python",
    names=["userId", "movieId", "rating", "timestamp"]
)

movies_ml = pd.read_csv(
    "/content/drive/MyDrive/HYBRID RECOMMENDER SYSTEM/movies.dat",
    sep="::",
    engine="python",
    names=["movieId", "title", "genres"],
    encoding="latin-1"
)

In [5]:
movies_ml.head()

   movieId                               title                        genres
0        1                    Toy Story (1995)   Animation|Children's|Comedy
1        2                      Jumanji (1995)  Adventure|Children's|Fantasy
2        3             Grumpier Old Men (1995)                Comedy|Romance
3        4            Waiting to Exhale (1995)                  Comedy|Drama
4        5  Father of the Bride Part II (1995)                        Comedy

In [6]:
movies_meta = pd.read_csv(
    "/content/drive/MyDrive/HYBRID RECOMMENDER SYSTEM/movies_metadata.xls",
    low_memory=False
)
# Keep only valid TMDB ids
movies_meta = movies_meta[movies_meta["id"].str.isnumeric()]
movies_meta["id"] = movies_meta["id"].astype(int)

In [7]:
credits = pd.read_csv('/content/drive/MyDrive/HYBRID RECOMMENDER SYSTEM/credits.xls')
keywords = pd.read_csv('/content/drive/MyDrive/HYBRID RECOMMENDER SYSTEM/keywords.xls')
tmdb = movies_meta.merge(credits, on="id") \
                   .merge(keywords, on="id")

In [8]:

tmdb.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count', 'cast', 'crew', 'keywords'],
      dtype='object')

In [9]:
tmdb["homepage"]

0        http://toystory.disney.com/toy-story
1                                         NaN
2                                         NaN
3                                         NaN
4                                         NaN
                         ...
46623    http://www.imdb.com/title/tt6209470/
46624                                     NaN
46625                                     NaN
46626                                     NaN
46627                                     NaN
Name: homepage, Length: 46628, dtype: object

In [10]:
tmdb["poster_path"]

0        /rhIRbceoE9lR4veEXuwCC2wARtG.jpg
1        /vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg
2        /6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg
3        /16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg
4        /e64sOI48hQXyru7naBFyssKFxVd.jpg
                       ...
46623    /jldsYflnId4tTWPx8es3uzsB1I8.jpg
46624    /xZkmxsNmYXJbKVsTRLLx3pqGHx7.jpg
46625    /d5bX92nDsISNhu3ZT69uHwmfCGw.jpg
46626    /aorBPO7ak8e8iJKT5OcqYxU3jlK.jpg
46627    /s5UkZt6NTsrS7ZF0Rh8nzupRlIU.jpg
Name: poster_path, Length: 46628, dtype: object

In [11]:
links = pd.read_csv(
    "/content/drive/MyDrive/HYBRID RECOMMENDER SYSTEM/links.xls"
)
# Clean ids
links = links.dropna(subset=["tmdbId", "movieId"])
links["tmdbId"] = links["tmdbId"].astype(int)

In [12]:
movies_common = movies_ml.merge(
    links[["movieId", "tmdbId"]],
    on="movieId",
    how="inner"
).merge(
    tmdb,
    left_on="tmdbId",
    right_on="id",
    how="inner"
)

In [13]:
print("MovieLens movies:", movies_ml.movieId.nunique())
print("Common movies:", movies_common.movieId.nunique())

MovieLens movies: 3883
Common movies: 3828

In [14]:
ratings.shape

(1000209, 4)

In [15]:
common_movie_ids = set(movies_common.movieId)

ratings_clean = ratings[
    ratings.movieId.isin(common_movie_ids)
]

In [16]:
ratings.shape

(1000209, 4)

In [17]:
ratings_clean.shape

(997407, 4)

In [18]:
ratings_clean

         userId  movieId  rating  timestamp
0             1     1193       5  978300760
1             1      661       3  978302109
2             1      914       3  978301968
3             1     3408       4  978300275
4             1     2355       5  978824291
...         ...      ...     ...        ...
1000204    6040     1091       1  956716541
1000205    6040     1094       5  956704887
1000206    6040      562       5  956704746
1000207    6040     1096       4  956715648
1000208    6040     1097       4  956715569

[997407 rows x 4 columns]

In [19]:
movies_common.isnull().sum()

movieId                     0
title_x                     0
genres_x                    0
tmdbId                      0
adult                       0
belongs_to_collection    3194
budget                      0
genres_y                    0
homepage                 3623
id                          0
imdb_id                     0
original_language           0
original_title              0
overview                   18
popularity                  0
poster_path                18
production_companies        0
production_countries        0
release_date                4
revenue                     0
runtime                     6
spoken_languages            0
status                      5
tagline                   941
title_y                     0
video                       0
vote_average                0
vote_count                  0
cast                        0
crew                        0
keywords                    0
dtype: int64

In [20]:
content_df = movies_common[[
    "movieId",
    "title_x",
    "overview",
    "genres_x",
    "keywords",
    "cast",
    "crew"
]].copy()

In [21]:
content_df.isnull().sum()

movieId      0
title_x      0
overview    18
genres_x     0
keywords     0
cast         0
crew         0
dtype: int64

In [22]:
content_df.rename(columns={"title_x":"title","genres_x":"genres"},inplace=True)

In [23]:
content_df.dropna(inplace=True)

In [24]:
content_df

,movieId,title,overview,genres,keywords,cast,crew
0,1,Toy Story (1995),"Led by Woody, Andy's toys live happily in his ...",Animation|Children's|Comedy,"[{'id': 931, 'name': 'jealousy'}, {'id': 4290,...","[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de..."
1,2,Jumanji (1995),When siblings Judy and Peter discover an encha...,Adventure|Children's|Fantasy,"[{'id': 10090, 'name': 'board game'}, {'id': 1...","[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de..."
2,3,Grumpier Old Men (1995),A family wedding reignites the ancient feud be...,Comedy|Romance,"[{'id': 1495, 'name': 'fishing'}, {'id': 12392...","[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de..."
3,4,Waiting to Exhale (1995),"Cheated on, mistreated and stepped on, the wom...",Comedy|Drama,"[{'id': 818, 'name': 'based on novel'}, {'id':...","[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de..."
4,5,Father of the Bride Part II (1995),Just when George Banks has recovered from his ...,Comedy,"[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...","[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de..."
...,...,...,...,...,...,...,...
3858,3948,Meet the Parents (2000),"Greg Focker is ready to marry his girlfriend, ...",Comedy,"[{'id': 591, 'name': 'cia'}, {'id': 822, 'name...","[{'cast_id': 1, 'character': 'Gaylord ""Greg"" F...","[{'credit_id': '52fe4303c3a36847f8033ca9', 'de..."
3859,3949,Requiem for a Dream (2000),The hopes and dreams of four ambitious people ...,Drama,"[{'id': 1803, 'name': 'drug addiction'}, {'id'...","[{'cast_id': 29, 'character': 'Sara Goldfarb',...","[{'credit_id': '52fe4263c3a36847f801a72b', 'de..."
3860,3950,Tigerland (2000),A group of recruits go through Advanced Infant...,Drama,"[{'id': 10183, 'name': 'independent film'}, {'...","[{'cast_id': 1, 'character': 'Pvt. Roland Bozz...","[{'credit_id': '52fe43a39251416c75018317', 'de..."
3861,3951,Two Family House (2000),Buddy Visalo (Michael Rispoli) is a factory wo...,Drama,[],"[{'cast_id': 1, 'character': 'Buddy Visalo', '...","[{'credit_id': '52fe46c2c3a368484e0a2471', 'de..."
3862,3952,"Contender, The (2000)",Political thriller about Laine Hanson's nomina...,Drama|Thriller,"[{'id': 6078, 'name': 'politics'}, {'id': 9937...","[{'cast_id': 1, 'character': 'Sheldon Runyon',...","[{'credit_id': '52fe4458c3a36847f809073f', 'de..."

In [25]:
content_df["genres"]=content_df["genres"].str.replace("|"," ")

In [26]:
content_df

,movieId,title,overview,genres,keywords,cast,crew
0,1,Toy Story (1995),"Led by Woody, Andy's toys live happily in his ...",Animation Children's Comedy,"[{'id': 931, 'name': 'jealousy'}, {'id': 4290,...","[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de..."
1,2,Jumanji (1995),When siblings Judy and Peter discover an encha...,Adventure Children's Fantasy,"[{'id': 10090, 'name': 'board game'}, {'id': 1...","[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de..."
2,3,Grumpier Old Men (1995),A family wedding reignites the ancient feud be...,Comedy Romance,"[{'id': 1495, 'name': 'fishing'}, {'id': 12392...","[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de..."
3,4,Waiting to Exhale (1995),"Cheated on, mistreated and stepped on, the wom...",Comedy Drama,"[{'id': 818, 'name': 'based on novel'}, {'id':...","[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de..."
4,5,Father of the Bride Part II (1995),Just when George Banks has recovered from his ...,Comedy,"[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...","[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de..."
...,...,...,...,...,...,...,...
3858,3948,Meet the Parents (2000),"Greg Focker is ready to marry his girlfriend, ...",Comedy,"[{'id': 591, 'name': 'cia'}, {'id': 822, 'name...","[{'cast_id': 1, 'character': 'Gaylord ""Greg"" F...","[{'credit_id': '52fe4303c3a36847f8033ca9', 'de..."
3859,3949,Requiem for a Dream (2000),The hopes and dreams of four ambitious people ...,Drama,"[{'id': 1803, 'name': 'drug addiction'}, {'id'...","[{'cast_id': 29, 'character': 'Sara Goldfarb',...","[{'credit_id': '52fe4263c3a36847f801a72b', 'de..."
3860,3950,Tigerland (2000),A group of recruits go through Advanced Infant...,Drama,"[{'id': 10183, 'name': 'independent film'}, {'...","[{'cast_id': 1, 'character': 'Pvt. Roland Bozz...","[{'credit_id': '52fe43a39251416c75018317', 'de..."
3861,3951,Two Family House (2000),Buddy Visalo (Michael Rispoli) is a factory wo...,Drama,[],"[{'cast_id': 1, 'character': 'Buddy Visalo', '...","[{'credit_id': '52fe46c2c3a368484e0a2471', 'de..."
3862,3952,"Contender, The (2000)",Political thriller about Laine Hanson's nomina...,Drama Thriller,"[{'id': 6078, 'name': 'politics'}, {'id': 9937...","[{'cast_id': 1, 'character': 'Sheldon Runyon',...","[{'credit_id': '52fe4458c3a36847f809073f', 'de..."

In [27]:
import ast

In [28]:
def extract_names(text):
    data=ast.literal_eval(text)
    return " ".join([d["name"] for d in data])

In [29]:
content_df["keywords"][0]

"[{'id': 931, 'name': 'jealousy'}, {'id': 4290, 'name': 'toy'}, {'id': 5202, 'name': 'boy'}, {'id': 6054, 'name': 'friendship'}, {'id': 9713, 'name': 'friends'}, {'id': 9823, 'name': 'rivalry'}, {'id': 165503, 'name': 'boy next door'}, {'id': 170722, 'name': 'new toy'}, {'id': 187065, 'name': 'toy comes to life'}]"

In [30]:
extract_names(content_df["keywords"][0])

'jealousy toy boy friendship friends rivalry boy next door new toy toy comes to life'

In [31]:
content_df["keywords"] = content_df["keywords"].apply(extract_names)
# content_df["cast"] = content_df["cast"].apply(extract_names)
# content_df["crew"] = content_df["crew"].apply(extract_names)

In [32]:
content_df

,movieId,title,overview,genres,keywords,cast,crew
0,1,Toy Story (1995),"Led by Woody, Andy's toys live happily in his ...",Animation Children's Comedy,jealousy toy boy friendship friends rivalry bo...,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de..."
1,2,Jumanji (1995),When siblings Judy and Peter discover an encha...,Adventure Children's Fantasy,board game disappearance based on children's b...,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de..."
2,3,Grumpier Old Men (1995),A family wedding reignites the ancient feud be...,Comedy Romance,fishing best friend duringcreditsstinger old men,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de..."
3,4,Waiting to Exhale (1995),"Cheated on, mistreated and stepped on, the wom...",Comedy Drama,based on novel interracial relationship single...,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de..."
4,5,Father of the Bride Part II (1995),Just when George Banks has recovered from his ...,Comedy,baby midlife crisis confidence aging daughter ...,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de..."
...,...,...,...,...,...,...,...
3858,3948,Meet the Parents (2000),"Greg Focker is ready to marry his girlfriend, ...",Comedy,cia airport cat jew orderly airplane father-in...,"[{'cast_id': 1, 'character': 'Gaylord ""Greg"" F...","[{'credit_id': '52fe4303c3a36847f8033ca9', 'de..."
3859,3949,Requiem for a Dream (2000),The hopes and dreams of four ambitious people ...,Drama,drug addiction junkie heroin speed diet unsoci...,"[{'cast_id': 29, 'character': 'Sara Goldfarb',...","[{'credit_id': '52fe4263c3a36847f801a72b', 'de..."
3860,3950,Tigerland (2000),A group of recruits go through Advanced Infant...,Drama,independent film awol fort polk louisiana targ...,"[{'cast_id': 1, 'character': 'Pvt. Roland Bozz...","[{'credit_id': '52fe43a39251416c75018317', 'de..."
3861,3951,Two Family House (2000),Buddy Visalo (Michael Rispoli) is a factory wo...,Drama,,"[{'cast_id': 1, 'character': 'Buddy Visalo', '...","[{'credit_id': '52fe46c2c3a368484e0a2471', 'de..."
3862,3952,"Contender, The (2000)",Political thriller about Laine Hanson's nomina...,Drama Thriller,politics suspense,"[{'cast_id': 1, 'character': 'Sheldon Runyon',...","[{'credit_id': '52fe4458c3a36847f809073f', 'de..."

In [33]:
content_df["cast"][0]

"[{'cast_id': 14, 'character': 'Woody (voice)', 'credit_id': '52fe4284c3a36847f8024f95', 'gender': 2, 'id': 31, 'name': 'Tom Hanks', 'order': 0, 'profile_path': '/pQFoyx7rp09CJTAb932F2g8Nlho.jpg'}, {'cast_id': 15, 'character': 'Buzz Lightyear (voice)', 'credit_id': '52fe4284c3a36847f8024f99', 'gender': 2, 'id': 12898, 'name': 'Tim Allen', 'order': 1, 'profile_path': '/uX2xVf6pMmPepxnvFWyBtjexzgY.jpg'}, {'cast_id': 16, 'character': 'Mr. Potato Head (voice)', 'credit_id': '52fe4284c3a36847f8024f9d', 'gender': 2, 'id': 7167, 'name': 'Don Rickles', 'order': 2, 'profile_path': '/h5BcaDMPRVLHLDzbQavec4xfSdt.jpg'}, {'cast_id': 17, 'character': 'Slinky Dog (voice)', 'credit_id': '52fe4284c3a36847f8024fa1', 'gender': 2, 'id': 12899, 'name': 'Jim Varney', 'order': 3, 'profile_path': '/eIo2jVVXYgjDtaHoF19Ll9vtW7h.jpg'}, {'cast_id': 18, 'character': 'Rex (voice)', 'credit_id': '52fe4284c3a36847f8024fa5', 'gender': 2, 'id': 12900, 'name': 'Wallace Shawn', 'order': 4, 'profile_path': '/oGE6JqPP2xH4tNORKNqxbNPYi7u.jpg'}, {'cast_id': 19, 'character': 'Hamm (voice)', 'credit_id': '52fe4284c3a36847f8024fa9', 'gender': 2, 'id': 7907, 'name': 'John Ratzenberger', 'order': 5, 'profile_path': '/yGechiKWL6TJDfVE2KPSJYqdMsY.jpg'}, {'cast_id': 20, 'character': 'Bo Peep (voice)', 'credit_id': '52fe4284c3a36847f8024fad', 'gender': 1, 'id': 8873, 'name': 'Annie Potts', 'order': 6, 'profile_path': '/eryXT84RL41jHSJcMy4kS3u9y6w.jpg'}, {'cast_id': 26, 'character': 'Andy (voice)', 'credit_id': '52fe4284c3a36847f8024fc1', 'gender': 0, 'id': 1116442, 'name': 'John Morris', 'order': 7, 'profile_path': '/vYGyvK4LzeaUCoNSHtsuqJUY15M.jpg'}, {'cast_id': 22, 'character': 'Sid (voice)', 'credit_id': '52fe4284c3a36847f8024fb1', 'gender': 2, 'id': 12901, 'name': 'Erik von Detten', 'order': 8, 'profile_path': '/twnF1ZaJ1FUNUuo6xLXwcxjayBE.jpg'}, {'cast_id': 23, 'character': 'Mrs. Davis (voice)', 'credit_id': '52fe4284c3a36847f8024fb5', 'gender': 1, 'id': 12133, 'name': 'Laurie Metcalf', 'order': 9, 'profile_path': '/unMMIT60eoBM2sN2nyR7EZ2BvvD.jpg'}, {'cast_id': 24, 'character': 'Sergeant (voice)', 'credit_id': '52fe4284c3a36847f8024fb9', 'gender': 2, 'id': 8655, 'name': 'R. Lee Ermey', 'order': 10, 'profile_path': '/r8GBqFBjypLUP9VVqDqfZ7wYbSs.jpg'}, {'cast_id': 25, 'character': 'Hannah (voice)', 'credit_id': '52fe4284c3a36847f8024fbd', 'gender': 1, 'id': 12903, 'name': 'Sarah Freeman', 'order': 11, 'profile_path': None}, {'cast_id': 27, 'character': 'TV Announcer (voice)', 'credit_id': '52fe4284c3a36847f8024fc5', 'gender': 2, 'id': 37221, 'name': 'Penn Jillette', 'order': 12, 'profile_path': '/zmAaXUdx12NRsssgHbk1T31j2x9.jpg'}]"

In [34]:
def convert_cast(text):
    return " ".join([d["name"] for d in ast.literal_eval(text)][:3])

In [35]:
content_df["cast"] = content_df["cast"].apply(convert_cast)

In [36]:
content_df.head()

,movieId,title,overview,genres,keywords,cast,crew
0,1,Toy Story (1995),"Led by Woody, Andy's toys live happily in his ...",Animation Children's Comedy,jealousy toy boy friendship friends rivalry bo...,Tom Hanks Tim Allen Don Rickles,"[{'credit_id': '52fe4284c3a36847f8024f49', 'de..."
1,2,Jumanji (1995),When siblings Judy and Peter discover an encha...,Adventure Children's Fantasy,board game disappearance based on children's b...,Robin Williams Jonathan Hyde Kirsten Dunst,"[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de..."
2,3,Grumpier Old Men (1995),A family wedding reignites the ancient feud be...,Comedy Romance,fishing best friend duringcreditsstinger old men,Walter Matthau Jack Lemmon Ann-Margret,"[{'credit_id': '52fe466a9251416c75077a89', 'de..."
3,4,Waiting to Exhale (1995),"Cheated on, mistreated and stepped on, the wom...",Comedy Drama,based on novel interracial relationship single...,Whitney Houston Angela Bassett Loretta Devine,"[{'credit_id': '52fe44779251416c91011acb', 'de..."
4,5,Father of the Bride Part II (1995),Just when George Banks has recovered from his ...,Comedy,baby midlife crisis confidence aging daughter ...,Steve Martin Diane Keaton Martin Short,"[{'credit_id': '52fe44959251416c75039ed7', 'de..."

In [37]:
content_df["crew"][0]

'[{\'credit_id\': \'52fe4284c3a36847f8024f49\', \'department\': \'Directing\', \'gender\': 2, \'id\': 7879, \'job\': \'Director\', \'name\': \'John Lasseter\', \'profile_path\': \'/7EdqiNbr4FRjIhKHyPPdFfEEEFG.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f4f\', \'department\': \'Writing\', \'gender\': 2, \'id\': 12891, \'job\': \'Screenplay\', \'name\': \'Joss Whedon\', \'profile_path\': \'/dTiVsuaTVTeGmvkhcyJvKp2A5kr.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f55\', \'department\': \'Writing\', \'gender\': 2, \'id\': 7, \'job\': \'Screenplay\', \'name\': \'Andrew Stanton\', \'profile_path\': \'/pvQWsu0qc8JFQhMVJkTHuexUAa1.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f5b\', \'department\': \'Writing\', \'gender\': 2, \'id\': 12892, \'job\': \'Screenplay\', \'name\': \'Joel Cohen\', \'profile_path\': \'/dAubAiZcvKFbboWlj7oXOkZnTSu.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f61\', \'department\': \'Writing\', \'gender\': 0, \'id\': 12893, \'job\': \'Screenplay\', \'name\': \'Alec Sokolow\', \'profile_path\': \'/v79vlRYi94BZUQnkkyznbGUZLjT.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f67\', \'department\': \'Production\', \'gender\': 1, \'id\': 12894, \'job\': \'Producer\', \'name\': \'Bonnie Arnold\', \'profile_path\': None}, {\'credit_id\': \'52fe4284c3a36847f8024f6d\', \'department\': \'Production\', \'gender\': 0, \'id\': 12895, \'job\': \'Executive Producer\', \'name\': \'Ed Catmull\', \'profile_path\': None}, {\'credit_id\': \'52fe4284c3a36847f8024f73\', \'department\': \'Production\', \'gender\': 2, \'id\': 12896, \'job\': \'Producer\', \'name\': \'Ralph Guggenheim\', \'profile_path\': None}, {\'credit_id\': \'52fe4284c3a36847f8024f79\', \'department\': \'Production\', \'gender\': 2, \'id\': 12897, \'job\': \'Executive Producer\', \'name\': \'Steve Jobs\', \'profile_path\': \'/mOMP3SwD5qWQSR0ldCIByd3guTV.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f8b\', \'department\': \'Editing\', \'gender\': 2, \'id\': 8, \'job\': \'Editor\', \'name\': \'Lee Unkrich\', \'profile_path\': \'/bdTCCXjgOV3YyaNmLGYGOxFQMOc.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f91\', \'department\': \'Art\', \'gender\': 2, \'id\': 7883, \'job\': \'Art Direction\', \'name\': \'Ralph Eggleston\', \'profile_path\': \'/uUfcGKDsKO1aROMpXRs67Hn6RvR.jpg\'}, {\'credit_id\': \'598331bf925141421201044b\', \'department\': \'Editing\', \'gender\': 2, \'id\': 1168870, \'job\': \'Editor\', \'name\': \'Robert Gordon\', \'profile_path\': None}, {\'credit_id\': \'5892168cc3a36809660095f9\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1552883, \'job\': \'Foley Editor\', \'name\': \'Mary Helen Leasman\', \'profile_path\': None}, {\'credit_id\': \'5531824d9251415289000945\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1453514, \'job\': \'Animation\', \'name\': \'Kim Blanchette\', \'profile_path\': None}, {\'credit_id\': \'589215969251412dcb009bf6\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1414182, \'job\': \'ADR Editor\', \'name\': \'Marilyn McCoppen\', \'profile_path\': None}, {\'credit_id\': \'589217099251412dc500a018\', \'department\': \'Sound\', \'gender\': 2, \'id\': 7885, \'job\': \'Orchestrator\', \'name\': \'Randy Newman\', \'profile_path\': \'/w0JzfoiM25nrnxYOzosPHRq6mlE.jpg\'}, {\'credit_id\': \'5693e6b29251417b0e0000e3\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1429549, \'job\': \'Color Timer\', \'name\': \'Dale E. Grahn\', \'profile_path\': None}, {\'credit_id\': \'572e2522c3a36869e6001a9c\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 7949, \'job\': \'CG Painter\', \'name\': \'Robin Cooper\', \'profile_path\': None}, {\'credit_id\': \'574f12309251415ca1000012\', \'department\': \'Writing\', \'gender\': 2, \'id\': 7879, \'job\': \'Original Story\', \'name\': \'John Lasseter\', \'profile_path\': \'/7EdqiNbr4FRjIhKHyPPdFfEEEFG.jpg\'}, {\'credit_id\': \'574f1240c3a3682e7300001c\', \'department\': \'Writing\', \'gender\': 2, \'id\': 12890, \'job\': \'Original Story\', \'name\': \'Pete Docter\', \'profile_path\': \'/r6ngPgnReA3RHmKjmSoVsc6Awjp.jpg\'}, {\'credit_id\': \'574f12519251415c92000015\', \'department\': \'Writing\', \'gender\': 0, \'id\': 7911, \'job\': \'Original Story\', \'name\': \'Joe Ranft\', \'profile_path\': \'/f1BoWC2JbCcfP1e5hKfGsxkHzVU.jpg\'}, {\'credit_id\': \'574f12cec3a3682e82000022\', \'department\': \'Crew\', \'gender\': 0, \'id\': 1629419, \'job\': \'Post Production Supervisor\', \'name\': \'Patsy Bouge\', \'profile_path\': None}, {\'credit_id\': \'574f14f19251415ca1000082\', \'department\': \'Art\', \'gender\': 0, \'id\': 7961, \'job\': \'Sculptor\', \'name\': \'Norm DeCarlo\', \'profile_path\': None}, {\'credit_id\': \'5751ae4bc3a3683772002b7f\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 12905, \'job\': \'Animation Director\', \'name\': \'Ash Brannon\', \'profile_path\': \'/6ueWgPEEBHvS3De2BHYQnYjRTig.jpg\'}, {\'credit_id\': \'5891edbe9251412dc5007cd6\', \'department\': \'Sound\', \'gender\': 2, \'id\': 7885, \'job\': \'Music\', \'name\': \'Randy Newman\', \'profile_path\': \'/w0JzfoiM25nrnxYOzosPHRq6mlE.jpg\'}, {\'credit_id\': \'589213d39251412dc8009832\', \'department\': \'Directing\', \'gender\': 0, \'id\': 1748707, \'job\': \'Layout\', \'name\': \'Roman Figun\', \'profile_path\': None}, {\'credit_id\': \'5892173dc3a3680968009351\', \'department\': \'Sound\', \'gender\': 2, \'id\': 4949, \'job\': \'Orchestrator\', \'name\': \'Don Davis\', \'profile_path\': None}, {\'credit_id\': \'589217cec3a3686b0a0052ba\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1372885, \'job\': \'Music Editor\', \'name\': \'James Flamberg\', \'profile_path\': None}, {\'credit_id\': \'58921831c3a3686348004a64\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1739962, \'job\': \'Negative Cutter\', \'name\': \'Mary Beth Smith\', \'profile_path\': None}, {\'credit_id\': \'58921838c3a36809700096c0\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1748513, \'job\': \'Negative Cutter\', \'name\': \'Rick Mackay\', \'profile_path\': None}, {\'credit_id\': \'589218429251412dd1009d1b\', \'department\': \'Art\', \'gender\': 0, \'id\': 1458006, \'job\': \'Title Designer\', \'name\': \'Susan Bradley\', \'profile_path\': None}, {\'credit_id\': \'5891ed99c3a3680966007670\', \'department\': \'Crew\', \'gender\': 0, \'id\': 1748557, \'job\': \'Supervising Technical Director\', \'name\': \'William Reeves\', \'profile_path\': None}, {\'credit_id\': \'5891edcec3a3686b0a002eb2\', \'department\': \'Sound\', \'gender\': 2, \'id\': 7885, \'job\': \'Songs\', \'name\': \'Randy Newman\', \'profile_path\': \'/w0JzfoiM25nrnxYOzosPHRq6mlE.jpg\'}, {\'credit_id\': \'5891edf9c3a36809700075e6\', \'department\': \'Writing\', \'gender\': 2, \'id\': 7, \'job\': \'Original Story\', \'name\': \'Andrew Stanton\', \'profile_path\': \'/pvQWsu0qc8JFQhMVJkTHuexUAa1.jpg\'}, {\'credit_id\': \'58920f0b9251412dd7009104\', \'department\': \'Crew\', \'gender\': 2, \'id\': 12890, \'job\': \'Supervising Animator\', \'name\': \'Pete Docter\', \'profile_path\': \'/r6ngPgnReA3RHmKjmSoVsc6Awjp.jpg\'}, {\'credit_id\': \'58920f1fc3a3680977009021\', \'department\': \'Sound\', \'gender\': 2, \'id\': 2216, \'job\': \'Sound Designer\', \'name\': \'Gary Rydstrom\', \'profile_path\': \'/jZpr1nVfO7lldWI0YtmP1FGw7Rj.jpg\'}, {\'credit_id\': \'58920f389251412dd700912d\', \'department\': \'Production\', \'gender\': 0, \'id\': 12909, \'job\': \'Production Supervisor\', \'name\': \'Karen Robert Jackson\', \'profile_path\': None}, {\'credit_id\': \'58920fbd9251412dcb00969c\', \'department\': \'Crew\', \'gender\': 0, \'id\': 953331, \'job\': \'Executive Music Producer\', \'name\': \'Chris Montan\', \'profile_path\': None}, {\'credit_id\': \'589210069251412dd7009219\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 7893, \'job\': \'Animation Director\', \'name\': \'Rich Quade\', \'profile_path\': None}, {\'credit_id\': \'589210329251412dcd00943b\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8025, \'job\': \'Animation\', \'name\': \'Michael Berenstein\', \'profile_path\': None}, {\'credit_id\': \'5892103bc3a368096a009180\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 78009, \'job\': \'Animation\', \'name\': \'Colin Brady\', \'profile_path\': None}, {\'credit_id\': \'5892105dc3a3680968008db2\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748682, \'job\': \'Animation\', \'name\': \'Davey Crockett Feiten\', \'profile_path\': None}, {\'credit_id\': \'589210669251412dcd009466\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1454030, \'job\': \'Animation\', \'name\': \'Angie Glocka\', \'profile_path\': None}, {\'credit_id\': \'5892107c9251412dd1009613\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748683, \'job\': \'Animation\', \'name\': \'Rex Grignon\', \'profile_path\': None}, {\'credit_id\': \'5892108ac3a3680973008d3f\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748684, \'job\': \'Animation\', \'name\': \'Tom K. Gurney\', \'profile_path\': None}, {\'credit_id\': \'58921093c3a3686348004477\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 8029, \'job\': \'Animation\', \'name\': \'Jimmy Hayward\', \'profile_path\': \'/lTDRpudEY7BDwTefXbXzMlmb0ui.jpg\'}, {\'credit_id\': \'5892109b9251412dcd0094b0\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1426773, \'job\': \'Animation\', \'name\': \'Hal T. Hickel\', \'profile_path\': None}, {\'credit_id\': \'589210a29251412dc5009a29\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8035, \'job\': \'Animation\', \'name\': \'Karen Kiser\', \'profile_path\': None}, {\'credit_id\': \'589210ccc3a3680977009191\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748688, \'job\': \'Animation\', \'name\': \'Anthony B. LaMolinara\', \'profile_path\': None}, {\'credit_id\': \'589210d7c3a3686b0a004c1f\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 587314, \'job\': \'Animation\', \'name\': \'Guionne Leroy\', \'profile_path\': None}, {\'credit_id\': \'589210e1c3a36809770091a7\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7918, \'job\': \'Animation\', \'name\': \'Bud Luckey\', \'profile_path\': \'/pcCh7G19FKMNijmPQg1PMH1btic.jpg\'}, {\'credit_id\': \'589210ee9251412dc200978a\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748689, \'job\': \'Animation\', \'name\': \'Les Major\', \'profile_path\': None}, {\'credit_id\': \'589210fa9251412dc8009595\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7892, \'job\': \'Animation\', \'name\': \'Glenn McQueen\', \'profile_path\': None}, {\'credit_id\': \'589211029251412dc8009598\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 555795, \'job\': \'Animation\', \'name\': \'Mark Oftedal\', \'profile_path\': None}, {\'credit_id\': \'5892110b9251412dc800959d\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7882, \'job\': \'Animation\', \'name\': \'Jeff Pidgeon\', \'profile_path\': \'/yLddkg5HcgbJg00cS13GVBnP0HY.jpg\'}, {\'credit_id\': \'58921113c3a36863480044e4\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8017, \'job\': \'Animation\', \'name\': \'Jeff Pratt\', \'profile_path\': None}, {\'credit_id\': \'5892111c9251412dcb0097e9\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1184140, \'job\': \'Animation\', \'name\': \'Steve Rabatich\', \'profile_path\': None}, {\'credit_id\': \'58921123c3a36809700090f6\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8049, \'job\': \'Animation\', \'name\': \'Roger Rose\', \'profile_path\': None}, {\'credit_id\': \'5892112b9251412dcb0097fb\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1509559, \'job\': \'Animation\', \'name\': \'Steve Segal\', \'profile_path\': None}, {\'credit_id\': \'589211349251412dc80095c3\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748691, \'job\': \'Animation\', \'name\': \'Doug Sheppeck\', \'profile_path\': None}, {\'credit_id\': \'5892113cc3a3680970009106\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8050, \'job\': \'Animation\', \'name\': \'Alan Sperling\', \'profile_path\': None}, {\'credit_id\': \'58921148c3a3686b0a004c99\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8010, \'job\': \'Animation\', \'name\': \'Doug Sweetland\', \'profile_path\': None}, {\'credit_id\': \'58921150c3a3680966009125\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8044, \'job\': \'Animation\', \'name\': \'David Tart\', \'profile_path\': None}, {\'credit_id\': \'589211629251412dc5009b00\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1454034, \'job\': \'Animation\', \'name\': \'Ken Willard\', \'profile_path\': None}, {\'credit_id\': \'589211c1c3a3686b0a004d28\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 7887, \'job\': \'Visual Effects Supervisor\', \'name\': \'Thomas Porter\', \'profile_path\': None}, {\'credit_id\': \'589211d4c3a3680968008ed9\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1406878, \'job\': \'Visual Effects\', \'name\': \'Mark Thomas Henne\', \'profile_path\': None}, {\'credit_id\': \'589211f59251412dd4008e65\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748698, \'job\': \'Visual Effects\', \'name\': \'Oren Jacob\', \'profile_path\': None}, {\'credit_id\': \'58921242c3a368096a00939b\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748699, \'job\': \'Visual Effects\', \'name\': \'Darwyn Peachey\', \'profile_path\': None}, {\'credit_id\': \'5892124b9251412dc5009bd2\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748701, \'job\': \'Visual Effects\', \'name\': \'Mitch Prater\', \'profile_path\': None}, {\'credit_id\': \'58921264c3a3686b0a004dbf\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748703, \'job\': \'Visual Effects\', \'name\': \'Brian M. Rosen\', \'profile_path\': None}, {\'credit_id\': \'589212709251412dcd009676\', \'department\': \'Lighting\', \'gender\': 1, \'id\': 12912, \'job\': \'Lighting Supervisor\', \'name\': \'Sharon Calahan\', \'profile_path\': None}, {\'credit_id\': \'5892127fc3a3686b0a004de5\', \'department\': \'Lighting\', \'gender\': 0, \'id\': 7899, \'job\': \'Lighting Supervisor\', \'name\': \'Galyn Susman\', \'profile_path\': None}, {\'credit_id\': \'589212cdc3a3680970009268\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 12915, \'job\': \'CG Painter\', \'name\': \'William Cone\', \'profile_path\': None}, {\'credit_id\': \'5892130f9251412dc8009791\', \'department\': \'Art\', \'gender\': 0, \'id\': 1748705, \'job\': \'Sculptor\', \'name\': \'Shelley Daniels Lekven\', \'profile_path\': None}, {\'credit_id\': \'5892131c9251412dd4008f4c\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7889, \'job\': \'Character Designer\', \'name\': \'Bob Pauley\', \'profile_path\': None}, {\'credit_id\': \'589213249251412dd100987b\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7918, \'job\': \'Character Designer\', \'name\': \'Bud Luckey\', \'profile_path\': \'/pcCh7G19FKMNijmPQg1PMH1btic.jpg\'}, {\'credit_id\': \'5892132b9251412dc80097b1\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7, \'job\': \'Character Designer\', \'name\': \'Andrew Stanton\', \'profile_path\': \'/pvQWsu0qc8JFQhMVJkTHuexUAa1.jpg\'}, {\'credit_id\': \'58921332c3a368634800467b\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 12915, \'job\': \'Character Designer\', \'name\': \'William Cone\', \'profile_path\': None}, {\'credit_id\': \'5892135f9251412dd4008f90\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748706, \'job\': \'Character Designer\', \'name\': \'Steve Johnson\', \'profile_path\': None}, {\'credit_id\': \'58921384c3a3680973008fd4\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1176752, \'job\': \'Character Designer\', \'name\': \'Dan Haskett\', \'profile_path\': None}, {\'credit_id\': \'5892138e9251412dc20099fc\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1088034, \'job\': \'Character Designer\', \'name\': \'Tom Holloway\', \'profile_path\': \'/a0r0T2usTBpgMI5aZbRBDW1fTl8.jpg\'}, {\'credit_id\': \'58921395c3a368097700942f\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1447465, \'job\': \'Character Designer\', \'name\': \'Jean Gillmore\', \'profile_path\': None}, {\'credit_id\': \'589213e2c3a3680973009026\', \'department\': \'Directing\', \'gender\': 0, \'id\': 1748709, \'job\': \'Layout\', \'name\': \'Desirée Mourad\', \'profile_path\': None}, {\'credit_id\': \'589214099251412dc5009d57\', \'department\': \'Art\', \'gender\': 0, \'id\': 1748710, \'job\': \'Set Dresser\', \'name\': "Kelly O\'Connell", \'profile_path\': None}, {\'credit_id\': \'58921411c3a3686b0a004f70\', \'department\': \'Art\', \'gender\': 0, \'id\': 1443471, \'job\': \'Set Dresser\', \'name\': \'Sonoko Konishi\', \'profile_path\': None}, {\'credit_id\': \'58921434c3a368096a00956e\', \'department\': \'Art\', \'gender\': 0, \'id\': 1748711, \'job\': \'Set Dresser\', \'name\': \'Ann M. Rockwell\', \'profile_path\': None}, {\'credit_id\': \'5892144ac3a36809680090de\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1748712, \'job\': \'Editorial Manager\', \'name\': \'Julie M. McDonald\', \'profile_path\': None}, {\'credit_id\': \'58921479c3a368096800910f\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1589729, \'job\': \'Assistant Editor\', \'name\': \'Robin Lee\', \'profile_path\': None}, {\'credit_id\': \'5892148b9251412dd10099cc\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1748716, \'job\': \'Assistant Editor\', \'name\': \'Tom Freeman\', \'profile_path\': None}, {\'credit_id\': \'589214959251412dcb009b1f\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1748717, \'job\': \'Assistant Editor\', \'name\': \'Ada Cochavi\', \'profile_path\': None}, {\'credit_id\': \'5892149ec3a3686348004798\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1336438, \'job\': \'Assistant Editor\', \'name\': \'Dana Mulligan\', \'profile_path\': None}, {\'credit_id\': \'589214adc3a368096a0095db\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1748718, \'job\': \'Editorial Coordinator\', \'name\': \'Deirdre Morrison\', \'profile_path\': None}, {\'credit_id\': \'589214c7c3a368097700952b\', \'department\': \'Production\', \'gender\': 0, \'id\': 1748719, \'job\': \'Production Coordinator\', \'name\': \'Lori Lombardo\', \'profile_path\': None}, {\'credit_id\': \'589214cec3a368096a009603\', \'department\': \'Production\', \'gender\': 0, \'id\': 1748720, \'job\': \'Production Coordinator\', \'name\': \'Ellen Devine\', \'profile_path\': None}, {\'credit_id\': \'589214e39251412dc8009904\', \'department\': \'Crew\', \'gender\': 0, \'id\': 1468014, \'job\': \'Unit Publicist\', \'name\': \'Lauren Beth Strogoff\', \'profile_path\': None}, {\'credit_id\': \'58921544c3a3686b0a00507d\', \'department\': \'Sound\', \'gender\': 2, \'id\': 2216, \'job\': \'Sound Re-Recording Mixer\', \'name\': \'Gary Rydstrom\', \'profile_path\': \'/jZpr1nVfO7lldWI0YtmP1FGw7Rj.jpg\'}, {\'credit_id\': \'5892154c9251412dd1009a56\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1425978, \'job\': \'Sound Re-Recording Mixer\', \'name\': \'Gary Summers\', \'profile_path\': None}, {\'credit_id\': \'58921555c3a36809680091bd\', \'department\': \'Sound\', \'gender\': 2, \'id\': 8276, \'job\': \'Supervising Sound Editor\', \'name\': \'Tim Holland\', \'profile_path\': None}, {\'credit_id\': \'589215c39251412dcb009c12\', \'department\': \'Sound\', \'gender\': 0, \'id\': 7069, \'job\': \'Sound Effects Editor\', \'name\': \'Pat Jackson\', \'profile_path\': None}, {\'credit_id\': \'58921698c3a368096a009788\', \'department\': \'Crew\', \'gender\': 2, \'id\': 15894, \'job\': \'Sound Design Assistant\', \'name\': \'Tom Myers\', \'profile_path\': None}, {\'credit_id\': \'589216a89251412dc2009ca4\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1414177, \'job\': \'Assistant Sound Editor\', \'name\': \'J.R. 

In [38]:
def convert_crew(text):
    return " ".join([d["name"] for d in ast.literal_eval(text) if d['job']=="Director"])

In [39]:
content_df["crew"] = content_df["crew"].apply(convert_crew)

In [40]:
content_df.head()

,movieId,title,overview,genres,keywords,cast,crew
0,1,Toy Story (1995),"Led by Woody, Andy's toys live happily in his ...",Animation Children's Comedy,jealousy toy boy friendship friends rivalry bo...,Tom Hanks Tim Allen Don Rickles,John Lasseter
1,2,Jumanji (1995),When siblings Judy and Peter discover an encha...,Adventure Children's Fantasy,board game disappearance based on children's b...,Robin Williams Jonathan Hyde Kirsten Dunst,Joe Johnston
2,3,Grumpier Old Men (1995),A family wedding reignites the ancient feud be...,Comedy Romance,fishing best friend duringcreditsstinger old men,Walter Matthau Jack Lemmon Ann-Margret,Howard Deutch
3,4,Waiting to Exhale (1995),"Cheated on, mistreated and stepped on, the wom...",Comedy Drama,based on novel interracial relationship single...,Whitney Houston Angela Bassett Loretta Devine,Forest Whitaker
4,5,Father of the Bride Part II (1995),Just when George Banks has recovered from his ...,Comedy,baby midlife crisis confidence aging daughter ...,Steve Martin Diane Keaton Martin Short,Charles Shyer

In [41]:
content_df["combined_features"] = (
    # content_df["overview"] + " " +
    (content_df["genres"] + " ") * 3 +
    content_df["keywords"] + " " +
    content_df["cast"]+" "+content_df["crew"]
)

In [42]:
# Clean genres
content_df["genres_clean"] = (
    content_df["genres"]
    .str.replace("|", " ", regex=False)
    .str.lower()
)

# Clean keywords (already space separated usually)
content_df["keywords_clean"] = (
    content_df["keywords"]
    .str.lower()
)

# Final explainable text
content_df["explainable_text"] = (
    content_df["genres_clean"] + " " +
    content_df["keywords_clean"]
)

In [43]:
content_df.head()

,movieId,title,overview,genres,keywords,cast,crew,combined_features,genres_clean,keywords_clean,explainable_text
0,1,Toy Story (1995),"Led by Woody, Andy's toys live happily in his ...",Animation Children's Comedy,jealousy toy boy friendship friends rivalry bo...,Tom Hanks Tim Allen Don Rickles,John Lasseter,Animation Children's Comedy Animation Children...,animation children's comedy,jealousy toy boy friendship friends rivalry bo...,animation children's comedy jealousy toy boy f...
1,2,Jumanji (1995),When siblings Judy and Peter discover an encha...,Adventure Children's Fantasy,board game disappearance based on children's b...,Robin Williams Jonathan Hyde Kirsten Dunst,Joe Johnston,Adventure Children's Fantasy Adventure Childre...,adventure children's fantasy,board game disappearance based on children's b...,adventure children's fantasy board game disapp...
2,3,Grumpier Old Men (1995),A family wedding reignites the ancient feud be...,Comedy Romance,fishing best friend duringcreditsstinger old men,Walter Matthau Jack Lemmon Ann-Margret,Howard Deutch,Comedy Romance Comedy Romance Comedy Romance f...,comedy romance,fishing best friend duringcreditsstinger old men,comedy romance fishing best friend duringcredi...
3,4,Waiting to Exhale (1995),"Cheated on, mistreated and stepped on, the wom...",Comedy Drama,based on novel interracial relationship single...,Whitney Houston Angela Bassett Loretta Devine,Forest Whitaker,Comedy Drama Comedy Drama Comedy Drama based o...,comedy drama,based on novel interracial relationship single...,comedy drama based on novel interracial relati...
4,5,Father of the Bride Part II (1995),Just when George Banks has recovered from his ...,Comedy,baby midlife crisis confidence aging daughter ...,Steve Martin Diane Keaton Martin Short,Charles Shyer,Comedy Comedy Comedy baby midlife crisis confi...,comedy,baby midlife crisis confidence aging daughter ...,comedy baby midlife crisis confidence aging da...

In [44]:
# from sklearn.feature_extraction.text import TfidfVectorizer

# tfidf = TfidfVectorizer(
#     stop_words="english",
#     max_features=10000,
#     ngram_range=(1, 2)
# )

# tfidf_matrix = tfidf.fit_transform(content_df["combined_features"])
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

tfidf_sim = TfidfVectorizer(
    stop_words="english",
    max_features=10000,
    ngram_range=(1, 2)
)

tfidf_matrix_sim = tfidf_sim.fit_transform(
    content_df["combined_features"]
)

In [45]:
# tfidf_matrix

In [46]:
# from sklearn.metrics.pairwise import cosine_similarity

# cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

In [47]:
# movie_index = pd.Series(
#     content_df.index,
#     index=content_df["movieId"]
# )

In [48]:
cosine_sim = cosine_similarity(
    tfidf_matrix_sim,
    tfidf_matrix_sim
)

In [49]:
movie_index = pd.Series(
    content_df.index,
    index=content_df["movieId"]
)

In [50]:
def recommend_movies_content(movie_id, top_n=10):
    if movie_id not in movie_index:
        return "Movie not found"

    idx = movie_index[movie_id]

    similarity_scores = list(
        enumerate(cosine_sim[idx])
    )

    similarity_scores = sorted(
        similarity_scores,
        key=lambda x: x[1],
        reverse=True
    )

    similarity_scores = similarity_scores[1:top_n + 1]

    movie_indices = [i[0] for i in similarity_scores]

    return content_df.iloc[movie_indices][["movieId", "title"]]

In [51]:
content_df[content_df["title"] == "Life (1999)"][["movieId", "title"]]

      movieId        title
2502     2587  Life (1999)

In [52]:
recommend_movies_content(movie_id=1	)

      movieId                                       title
3032     3114                          Toy Story 2 (1999)
1055     1064      Aladdin and the King of Thieves (1996)
2061     2142  American Tail: Fievel Goes West, An (1991)
2060     2141                    American Tail, An (1986)
2270     2355                        Bug's Life, A (1998)
3524     3611                       Saludos Amigos (1943)
589       596                            Pinocchio (1940)
3664     3751                          Chicken Run (2000)
2269     2354                   Rugrats Movie, The (1998)
240       244                     Gumby: The Movie (1995)

In [53]:
content_df.sample(10)

,movieId,title,overview,genres,keywords,cast,crew,combined_features,genres_clean,keywords_clean,explainable_text
1150,1169,American Dream (1990),Chronicles the six-month strike at Hormel in A...,Documentary,woman director,Jesse Jackson Juan Munoz Ray Rogers,Barbara Kopple Cathy Caplan Tom Haneke Lawrenc...,Documentary Documentary Documentary woman dire...,documentary,woman director,documentary woman director
2500,2585,"Lovers of the Arctic Circle, The (Los Amantes ...",Otto and Ana are kids when they meet each othe...,Drama Romance,suicide love at first sight brother sister rel...,Najwa Nimri Fele Martínez Joost Siedhoff,Julio Médem,Drama Romance Drama Romance Drama Romance suic...,drama romance,suicide love at first sight brother sister rel...,drama romance suicide love at first sight brot...
61,62,Mr. Holland's Opus (1995),"In 1965, passionate musician Glenn Holland tak...",Drama,composer mentor deaf-mute musical apprentice p...,Richard Dreyfuss Glenne Headly Jay Thomas,Stephen Herek,Drama Drama Drama composer mentor deaf-mute mu...,drama,composer mentor deaf-mute musical apprentice p...,drama composer mentor deaf-mute musical appren...
504,509,"Piano, The (1993)","After a long voyage from Scotland, pianist Ada...",Drama Romance,love triangle scotland mother adultery sexuali...,Holly Hunter Harvey Keitel Sam Neill,Jane Campion,Drama Romance Drama Romance Drama Romance love...,drama romance,love triangle scotland mother adultery sexuali...,drama romance love triangle scotland mother ad...
3076,3158,"Emperor and the Assassin, The (Jing ke ci qin ...","In pre-unified China, the King of Qin sends hi...",Drama,china assassin kingdom occupying power governa...,Gong Li Zhang Fengyi Sun Zhou,Chen Kaige,Drama Drama Drama china assassin kingdom occup...,drama,china assassin kingdom occupying power governa...,drama china assassin kingdom occupying power g...
2091,2172,"Strike! (a.k.a. All I Wanna Do, The Hairy Bird...",If there's one thing this wild group of friend...,Comedy,woman director,Kirsten Dunst Gaby Hoffmann Lynn Redgrave,Sarah Kernochan,Comedy Comedy Comedy woman director Kirsten Du...,comedy,woman director,comedy woman director
128,130,Angela (1995),A ten year old girl named Angela leads her six...,Drama,independent film woman director,Miranda Rhyne Charlotte Eve Blythe Anna Levine,Rebecca Miller,Drama Drama Drama independent film woman direc...,drama,independent film woman director,drama independent film woman director
1674,1728,"Winter Guest, The (1997)",The plot of the story is interactions between ...,Drama,independent film,Emma Thompson Phyllida Law Sheila Reid,Alan Rickman,Drama Drama Drama independent film Emma Thomps...,drama,independent film,drama independent film
3405,3491,My Chauffeur (1986),A feisty young woman accepts a mysterious offe...,Comedy,,Deborah Foreman Sam J. Jones Howard Hesseman,David Beaird,Comedy Comedy Comedy Deborah Foreman Sam J. J...,comedy,,comedy
274,278,Miami Rhapsody (1995),Gwyn Marcus has always wanted a marriage like ...,Comedy,,Sarah Jessica Parker Antonio Banderas Mia Farrow,David Frankel,Comedy Comedy Comedy Sarah Jessica Parker Ant...,comedy,,comedy

In [54]:
ratings_clean

         userId  movieId  rating  timestamp
0             1     1193       5  978300760
1             1      661       3  978302109
2             1      914       3  978301968
3             1     3408       4  978300275
4             1     2355       5  978824291
...         ...      ...     ...        ...
1000204    6040     1091       1  956716541
1000205    6040     1094       5  956704887
1000206    6040      562       5  956704746
1000207    6040     1096       4  956715648
1000208    6040     1097       4  956715569

[997407 rows x 4 columns]

In [55]:
!pip install scikit-surprise

Requirement already satisfied: scikit-surprise in /usr/local/lib/python3.12/dist-packages (1.1.4)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise) (1.5.3)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise) (1.17.1)

In [56]:
import surprise
print(surprise.__version__)

1.1.4

In [60]:
!pip install scikit-surprise

Requirement already satisfied: scikit-surprise in /usr/local/lib/python3.12/dist-packages (1.1.4)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise) (1.5.3)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise) (2.4.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise) (1.17.1)

In [62]:
!pip install numpy==1.26.4

Collecting numpy==1.26.4
  Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.4.3
    Uninstalling numpy-2.4.3:
      Successfully uninstalled numpy-2.4.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
shap 0.51.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
tobler 0.13.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
Successfully installed numpy-1.26.4

In [57]:
from surprise import Dataset, Reader, SVD, accuracy
from surprise.model_selection import train_test_split
import math

In [58]:
reader = Reader(rating_scale=(0.5, 5.0))

data = Dataset.load_from_df(
    ratings_clean[["userId", "movieId", "rating"]],
    reader
)

In [59]:
svd = SVD(
    n_factors=100,
    n_epochs=20,
    lr_all=0.005,
    reg_all=0.02,
    random_state=42
)

In [60]:
trainset, testset = train_test_split(
    data,
    test_size=0.2,
    random_state=42
)

svd.fit(trainset)

In [61]:
def cf_score(user_id, movie_id):
    return svd.predict(user_id, movie_id).est

In [62]:
def rank_movies_cf(user_id, candidate_movie_ids, top_n=10):
    scores = []

    for movie_id in candidate_movie_ids:
        score = cf_score(user_id, movie_id)
        scores.append((movie_id, score))

    scores.sort(key=lambda x: x[1], reverse=True)
    return scores[:top_n]

In [63]:
predictions = svd.test(testset)

In [64]:
# Step 1: get candidates from content-based model
content_candidates = recommend_movies_content(movie_id=1, top_n=10)["movieId"]

# Step 2: rank them using CF
ranked = rank_movies_cf(user_id=10, candidate_movie_ids=content_candidates)

# Step 3: show ranked movies
ranked_movies = pd.DataFrame(ranked, columns=["movieId", "cf_score"])
ranked_movies.merge(
    content_df[["movieId", "title"]],
    on="movieId"
)

   movieId  cf_score                                       title
0     3751  4.867838                          Chicken Run (2000)
1     3114  4.349145                          Toy Story 2 (1999)
2     2141  4.223761                    American Tail, An (1986)
3     2355  4.212605                        Bug's Life, A (1998)
4      596  3.907944                            Pinocchio (1940)
5     2142  3.892748  American Tail: Fievel Goes West, An (1991)
6     3611  3.662182                       Saludos Amigos (1943)
7     1064  3.613853      Aladdin and the King of Thieves (1996)
8      244  3.471190                     Gumby: The Movie (1995)
9     2354  3.335601                   Rugrats Movie, The (1998)

In [65]:
!pip install shap

Requirement already satisfied: shap in /usr/local/lib/python3.12/dist-packages (0.51.0)
Collecting numpy>=2 (from shap)
  Using cached numpy-2.4.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from shap) (1.17.1)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from shap) (1.6.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from shap) (2.2.2)
Requirement already satisfied: tqdm>=4.27.0 in /usr/local/lib/python3.12/dist-packages (from shap) (4.67.3)
Requirement already satisfied: packaging>20.9 in /usr/local/lib/python3.12/dist-packages (from shap) (26.0)
Requirement already satisfied: slicer==0.0.8 in /usr/local/lib/python3.12/dist-packages (from shap) (0.0.8)
Requirement already satisfied: numba in /usr/local/lib/python3.12/dist-packages (from shap) (0.60.0)
Requirement already satisfied: llvmlite in /usr/local/lib/python3.12/dist-packages (from shap) (0.43.0)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from shap) (3.1.2)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from shap) (4.15.0)
  Downloading numpy-2.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.9/60.9 kB 2.0 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->shap) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->shap) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->shap) (2025.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->shap) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->shap) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->shap) (1.17.0)
Downloading numpy-2.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (19.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.2/19.2 MB 21.3 MB/s eta 0:00:00
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
Successfully installed numpy-2.0.2

In [66]:
# import shap
# import numpy as np

# def similarity_model(X):
#     return cosine_similarity(X, reference_vector).ravel()

In [67]:
# explanations = {}

# for movie_id in content_candidates_df["movieId"]:
#     shap_df = explain_content_similarity(
#         seed_movie_id=1,
#         candidate_movie_id=movie_id,
#         top_k=5
#     )
#     explanations[movie_id] = shap_df["feature"].tolist()

In [68]:
content_df["genres_clean"] = (
    content_df["genres"]
    .str.replace("|", " ", regex=False)
    .str.lower()
)

In [69]:
def get_set(series_value):
    if isinstance(series_value, str):
        return set(series_value.lower().split())
    return set()

In [70]:
def generate_rich_explanation(seed_movie_id, candidate_movie_id):
    # Seed movie data
    seed_row = content_df[content_df["movieId"] == seed_movie_id].iloc[0]
    cand_row = content_df[content_df["movieId"] == candidate_movie_id].iloc[0]

    seed_title = seed_row["title"]

    # Genres
    seed_genres = get_set(seed_row["genres_clean"])
    cand_genres = get_set(cand_row["genres_clean"])
    shared_genres = seed_genres.intersection(cand_genres)

    # Cast
    seed_cast = get_set(seed_row["cast"])
    cand_cast = get_set(cand_row["cast"])
    shared_cast = seed_cast.intersection(cand_cast)

    # Director
    seed_director = seed_row.get("crew", "")
    cand_director = cand_row.get("crew", "")
    same_director = (
        isinstance(seed_director, str)
        and isinstance(cand_director, str)
        and seed_director.lower() == cand_director.lower()
        and seed_director != ""
    )

    reasons = []

    if shared_genres:
        reasons.append(
            "shared genres like " +
            ", ".join([g.title() for g in list(shared_genres)[:2]])
        )

    if shared_cast:
        reasons.append(
            "common cast members such as " +
            ", ".join([c.title() for c in list(shared_cast)[:2]])
        )

    if same_director:
        reasons.append(
            f"the same director ({seed_director})"
        )

    if not reasons:
        return (
            f"Recommended because it is similar in overall theme to "
            f"'{seed_title}'."
        )

    return (
        f"Recommended because it shares "
        + ", and ".join(reasons)
        + f" with '{seed_title}'."
    )

In [71]:
seed_movie_id = 2

content_candidates = recommend_movies_content(
    movie_id=seed_movie_id,
    top_n=10
)

explanations = {}

for movie_id in content_candidates["movieId"]:
    explanations[movie_id] = generate_rich_explanation(
        seed_movie_id,
        movie_id
    )

In [72]:
ranked = rank_movies_cf(
    user_id=10,
    candidate_movie_ids=content_candidates["movieId"].tolist()
)

ranked_df = (
    pd.DataFrame(ranked, columns=["movieId", "cf_score"])
    .merge(content_df[["movieId", "title"]], on="movieId")
)

In [73]:
ranked_df["explanation"] = ranked_df["movieId"].apply(
    lambda x: explanations[x]
)

ranked_df

,movieId,cf_score,title,explanation
0,2161,4.883018,"NeverEnding Story, The (1984)",Recommended because it shares shared genres li...
1,1967,4.874100,Labyrinth (1986),Recommended because it shares shared genres li...
2,2005,4.333994,"Goonies, The (1985)",Recommended because it shares shared genres li...
3,2043,4.225967,Darby O'Gill and the Little People (1959),Recommended because it shares shared genres li...
4,1009,4.118782,Escape to Witch Mountain (1975),Recommended because it shares shared genres li...
5,60,4.004665,"Indian in the Cupboard, The (1995)",Recommended because it shares shared genres li...
6,2399,3.678919,Santa Claus: The Movie (1985),Recommended because it shares shared genres li...
7,56,3.299471,Kids of the Round Table (1995),Recommended because it shares shared genres li...
8,2162,2.851041,"NeverEnding Story II: The Next Chapter, The (1...",Recommended because it shares shared genres li...
9,126,2.727981,"NeverEnding Story III, The (1994)",Recommended because it shares shared genres li...

In [74]:
ranked_df["explanation"][8]

"Recommended because it shares shared genres like Children'S, Fantasy, and common cast members such as Jonathan with 'Jumanji (1995)'."

In [75]:
content_df

,movieId,title,overview,genres,keywords,cast,crew,combined_features,genres_clean,keywords_clean,explainable_text
0,1,Toy Story (1995),"Led by Woody, Andy's toys live happily in his ...",Animation Children's Comedy,jealousy toy boy friendship friends rivalry bo...,Tom Hanks Tim Allen Don Rickles,John Lasseter,Animation Children's Comedy Animation Children...,animation children's comedy,jealousy toy boy friendship friends rivalry bo...,animation children's comedy jealousy toy boy f...
1,2,Jumanji (1995),When siblings Judy and Peter discover an encha...,Adventure Children's Fantasy,board game disappearance based on children's b...,Robin Williams Jonathan Hyde Kirsten Dunst,Joe Johnston,Adventure Children's Fantasy Adventure Childre...,adventure children's fantasy,board game disappearance based on children's b...,adventure children's fantasy board game disapp...
2,3,Grumpier Old Men (1995),A family wedding reignites the ancient feud be...,Comedy Romance,fishing best friend duringcreditsstinger old men,Walter Matthau Jack Lemmon Ann-Margret,Howard Deutch,Comedy Romance Comedy Romance Comedy Romance f...,comedy romance,fishing best friend duringcreditsstinger old men,comedy romance fishing best friend duringcredi...
3,4,Waiting to Exhale (1995),"Cheated on, mistreated and stepped on, the wom...",Comedy Drama,based on novel interracial relationship single...,Whitney Houston Angela Bassett Loretta Devine,Forest Whitaker,Comedy Drama Comedy Drama Comedy Drama based o...,comedy drama,based on novel interracial relationship single...,comedy drama based on novel interracial relati...
4,5,Father of the Bride Part II (1995),Just when George Banks has recovered from his ...,Comedy,baby midlife crisis confidence aging daughter ...,Steve Martin Diane Keaton Martin Short,Charles Shyer,Comedy Comedy Comedy baby midlife crisis confi...,comedy,baby midlife crisis confidence aging daughter ...,comedy baby midlife crisis confidence aging da...
...,...,...,...,...,...,...,...,...,...,...,...
3858,3948,Meet the Parents (2000),"Greg Focker is ready to marry his girlfriend, ...",Comedy,cia airport cat jew orderly airplane father-in...,Ben Stiller Robert De Niro Teri Polo,Jay Roach,Comedy Comedy Comedy cia airport cat jew order...,comedy,cia airport cat jew orderly airplane father-in...,comedy cia airport cat jew orderly airplane fa...
3859,3949,Requiem for a Dream (2000),The hopes and dreams of four ambitious people ...,Drama,drug addiction junkie heroin speed diet unsoci...,Ellen Burstyn Jared Leto Jennifer Connelly,Darren Aronofsky,Drama Drama Drama drug addiction junkie heroin...,drama,drug addiction junkie heroin speed diet unsoci...,drama drug addiction junkie heroin speed diet ...
3860,3950,Tigerland (2000),A group of recruits go through Advanced Infant...,Drama,independent film awol fort polk louisiana targ...,Colin Farrell Matthew Davis Clifton Collins Jr,Joel Schumacher,Drama Drama Drama independent film awol fort p...,drama,independent film awol fort polk louisiana targ...,drama independent film awol fort polk louisian...
3861,3951,Two Family House (2000),Buddy Visalo (Michael Rispoli) is a factory wo...,Drama,,Michael Rispoli Kelly Macdonald Kathrine Narducci,Raymond De Felitta,Drama Drama Drama Michael Rispoli Kelly Macdo...,drama,,drama
3862,3952,"Contender, The (2000)",Political thriller about Laine Hanson's nomina...,Drama Thriller,politics suspense,Gary Oldman Joan Allen Jeff Bridges,Rod Lurie,Drama Thriller Drama Thriller Drama Thriller p...,drama thriller,politics suspense,drama thriller politics suspense

In [76]:
rmse = accuracy.rmse(predictions)

RMSE: 0.8737

In [77]:
def get_relevant_items(testset, threshold=4.0):
    relevant = {}

    for uid, iid, true_r in testset:
        if true_r >= threshold:
            relevant.setdefault(uid, set()).add(iid)

    return relevant

relevant_items = get_relevant_items(testset)

In [78]:
def get_top_k_predictions(model, testset, k=10):
    user_predictions = {}

    for uid, iid, true_r in testset:
        est = model.predict(uid, iid).est
        user_predictions.setdefault(uid, []).append((iid, est))

    # Sort predictions for each user
    for uid in user_predictions:
        user_predictions[uid].sort(key=lambda x: x[1], reverse=True)
        user_predictions[uid] = user_predictions[uid][:k]

    return user_predictions

top_k_preds = get_top_k_predictions(svd, testset, k=10)

In [79]:
def precision_recall_at_k(relevant, predicted, k=10):
    precisions = []
    recalls = []

    for uid in relevant:
        if uid not in predicted:
            continue

        pred_items = {iid for iid, _ in predicted[uid]}
        rel_items = relevant[uid]

        tp = len(pred_items & rel_items)

        precisions.append(tp / k)
        recalls.append(tp / len(rel_items))

    return (
        sum(precisions) / len(precisions),
        sum(recalls) / len(recalls)
    )

precision, recall = precision_recall_at_k(
    relevant_items,
    top_k_preds,
    k=10
)

print("Precision@10:", precision)
print("Recall@10:", recall)

Precision@10: 0.6850425212606303
Recall@10: 0.641410068125028

In [80]:
def ndcg_at_k(relevant, predicted, k=10):
    ndcgs = []

    for uid in relevant:
        if uid not in predicted:
            continue

        dcg = 0.0
        for rank, (iid, _) in enumerate(predicted[uid], start=1):
            if iid in relevant[uid]:
                dcg += 1 / math.log2(rank + 1)

        ideal_dcg = sum(
            1 / math.log2(rank + 1)
            for rank in range(1, min(len(relevant[uid]), k) + 1)
        )

        if ideal_dcg > 0:
            ndcgs.append(dcg / ideal_dcg)

    return sum(ndcgs) / len(ndcgs)

ndcg = ndcg_at_k(
    relevant_items,
    top_k_preds,
    k=10
)

print("NDCG@10:", ndcg)

NDCG@10: 0.873798409954208